project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Understanding NYC Traffic Congestion: A Machine Learning Interpretability Approach"
  author: "Lilly Loghmani"
  date: "2025-05-05"
  chapters:
    - index.qmd
    - data.qmd
    - analysis.qmd
    - results.qmd
    - conclusion.qmd
  page-footer:
    left: |
      NYC Traffic Analysis
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    background: light

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    html-math-method: katex
    
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true

bibliography: references.bib


